plugins {
    id 'java'
}

def pluginGroup = "com.lazyz.wrtpkill"
def pluginName = "WRTPKILL"
def pluginAuthor = "Lazyz"

group = pluginGroup
version = '1.1.0'

repositories {
    mavenCentral()
    maven { url 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testImplementation 'org.yaml:snakeyaml:2.6'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.13.4'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
}

processResources {
    def props = [
            "group"  : project.group,
            "name"   : pluginName,
            "version": project.version,
            "author" : pluginAuthor
    ]
    inputs.properties(props)
    filteringCharset = 'UTF-8'

    filesMatching('plugin.yml') {
        expand(props)
    }
}
